### PR TITLE
Add embedded css and javascript

### PR DESCRIPTION
**Pull request by burodepeper**

### CODE REVIEW

**Comment by simurai** [comment]
Shouldn't the GA go at the end just before the close `</body>` or in the `<head>`?

**Comment by burodepeper** [comment]
> Voeg vervolgens deze regel aan elke sjabloonpagina toe, onmiddellijk na de openingstag <body>:

Rough translation from Dutch: _Add this stuff to your template, directly following the opening `<body>` tag_.

**Comment by simurai** [comment]
Is that the official guide?

> Paste your snippet (unaltered, in its entirety) into every web page you want to track. Paste it immediately before the closing </head> tag.

https://support.google.com/analytics/answer/1008080?hl=en

**Comment by burodepeper** [comment]
So, who shall we believe? The Americans or the Dutch?

**Comment by simurai** [comment]
Hehe..

HTML5 boilerplate still puts it at the end: https://github.com/h5bp/html5-boilerplate/blob/master/src/index.html#L30-L38

**Comment by burodepeper** [comment]
On atom.io it's in the `<head>`. I think it doesn't really matter.
I'll put it somewhere else, when I add a proper example of embedded javascript.
Just leave this PR open for now.

**Comment by simurai** [comment]
Yeah right, for the purpose of this repo it actually matters even less. I'll merge it and you can still change it later if you like.

**Comment by burodepeper** [comment]
:+1:

**Pull request merged**
